---
- name: Deploy Kubernetes Application
  hosts: k8s 
  gather_facts: yes 

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/Ansible/deployment.yaml  
        dest: /home/ubuntu/
      become: yes  
      become_user: root  

    - name: Apply Deployment
      command: kubectl apply -f /home/ubuntu/deployment.yaml
